### PR TITLE
Fixes #177, --packages and --excludePackages filtering

### LINKED ISSUE #177: --packages and --excludePackages flags don't work with some output formats
### Version
license-checker@22.0.0

### Expected
Given the following input I would expect `mkpkg` to be ignored:

```
license-checker --excludePackages="mypkg"
```

### Actual
`mypkg` is included in the output.

### Observations
From looking at the code, this bug is introduced by the coloring functionality; this means that the `.includes()` check will fail as the colorised string does not match the user's CLI input (which is not colorised).

### PR DESCRIPTION
**Pull request by jonny-improbable**
The filtering logic for both `--packages` and `--excludePackages` was broken if the output was being colorized.

To work around this I have moved the colorization out of the parsing logic and into the formatting.

WRT to removing `strip-ansi`, I'm not convinced this package was actually being imported anywhere before this change, but I couldn't find  it referenced anywhere in the code so I've removed it for good hygine.

### CODE REVIEW

File: bin/license-checker [hunk 1]
```diff
@@ -72,6 +67,17 @@ checker.init(args, function(err, json) {
         console.error('Found error');
         console.error(err);
     }
+
+    if (shouldColorizeOutput(args)) {
+        var keys = Object.keys(json);
+        keys.forEach(function(key) {
```
Comment (jonny-improbable) [inline bin/license-checker]: This is a little bit ugly; tbh the colorisation of the key should be performed inside the formatter, however this is a pragmatic fix if you're OK with it for now :)

File: lib/index.js [hunk 2]
```diff
@@ -35,12 +34,6 @@ var flatten = function(options) {
         readmeFile,
         licenseData, dirFiles, files = [], noticeFiles = [], licenseFile;
 
-    /*istanbul ignore next*/
-    if (colorize) {
-        moduleInfo = { licenses: chalk.bold.red(UNKNOWN) };
```
Comment (jonny-improbable) [inline lib/index.js]: initialising the license had nothing to do with colorising.

**Comment by davglass** [comment]
Published in `license-checker@23.0.0`
